### ISSUE TITLE
Updating data doesn't work with Android

### ISSUE THREAD

**Issue by NirpE** [JesperLekland/react-native-svg-charts#228]
### What is the problem?
BarChart freezes with Android when data is dynamically updated.

### When does it happen?
First time render works properly, but after updating chart data Android freezes.

### What platform?
* [ ] iOS
* [x] Android

React Native version: 0.54.0

### Stacktrace
```
E/unknown:ReactNative: Exception in native call
    com.facebook.react.uimanager.IllegalViewOperationException: Trying to remove a view index above child count 31 view tag: 689
     detail: View tag:689
      children(0): [
     ],
      indicesToRemove(1): [
    31,
     ],
      tagsToDelete(1): [
    620,
     ]
    
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:352)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:180)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:822)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:929)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:989)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by skymax406** [comment]
Hello I have save issue if I make a SVG line in my chart.

```
 <BarChart
                    // animate={true}
                    // animateDuration={1000}
                    style={{height: 180, marginHorizontal: 20}}
                    data={barData}
                    yAccessor={({item}) => item.value}
                    contentInset={{top: 5, bottom: 5}}
                >
                    <AxisLine/>
</BarChart>
```

```
const AxisLine = ({x, y, bandwidth}) => {

                    return (
                        <Line
                            key={"line" + index}
                            x1={0}
                            y1={middlePoint}
                            x2={100}
                            y2={middlePoint}
                            stroke="white"
                            strokeWidth="2"
                        />
                    )
}
```

I a make a change on my view, and not on my chart, I have the same issue. I've tested with version lower than 5.0 and it working, but I dont have my line ...

In version 5.2.0, everything is working if I comment my <AxisLine />

**Comment by JasonStu** [comment]
> Hello I have save issue if I make a SVG line in my chart.
> 
> ```
>  <BarChart
>                     // animate={true}
>                     // animateDuration={1000}
>                     style={{height: 180, marginHorizontal: 20}}
>                     data={barData}
>                     yAccessor={({item}) => item.value}
>                     contentInset={{top: 5, bottom: 5}}
>                 >
>                     <AxisLine/>
> </BarChart>
> ```
> ```
> const AxisLine = ({x, y, bandwidth}) => {
> 
>                     return (
>                         <Line
>                             key={"line" + index}
>                             x1={0}
>                             y1={middlePoint}
>                             x2={100}
>                             y2={middlePoint}
>                             stroke="white"
>                             strokeWidth="2"
>                         />
>                     )
> }
> ```
> If I make a change on my view, and not on my chart, I have the same issue.
> I've tested with lower version than 5.0 and it'sworking, but I don't have my line ...
> 
> In version 5.2.0, everything is working if I remove my AxisLine
hey gays ! Do you fix this issue

**Comment by JasonStu** [comment]
@skymax406 Do you have any idea to fix this?

**Comment by usrbowe** [comment]
Closing stale issue.
